'use strict';

(function () {

  var MIN_HASHTAG_LENGTH = 1;
  var MAX_HASHTAG_LENGTH = 20;
  var MAX_HASHTAGS = 5;
  var DEFAULT_EFFECT_VALUE = 100;

  window.data = {
    DEFAULT_EFFECT_VALUE: DEFAULT_EFFECT_VALUE,
    MAX_HASHTAGS: MAX_HASHTAGS,
    MIN_HASHTAG_LENGTH: MIN_HASHTAG_LENGTH,
    MAX_HASHTAG_LENGTH: MAX_HASHTAG_LENGTH
  };
})();
